### ISSUE TITLE
Is it possible to configure NTS sources?

### ISSUE THREAD

**Issue by FallingSnow** [cturra/docker-ntp#49] opened 2022-05-08 02:12 UTC
Wondering if there is a variable like `NTP_SERVERS` for NTS sources.

**Comment by cturra** [comment] 2022-05-24 21:29
thanks for your patience with my reply! i somehow missed your issue.

unfortunately there's a lot more to configure when setting up NTS sources, like a doing cerificate signing with a root CA (like let's encrypt) for the chrony process. this would all need to be done as part of the bootstrapping process since, by design, this container doesn't keep any state and is therefore fully immutable. while certainly possible, i'd suggest it would be outside the scope of this project, which is meant to be a simple NTP server.

i'm going to close this off, but if you want to help take a stab at a NTS server fork of this contain, i'd be happy to assist. thanks for your suggestion!

**Closed by cturra** 2022-05-24 21:29 UTC
